#!/usr/bin/env bash
# One-time setup of a local 3-node Mpcium cluster (2-of-3 threshold) under mpc/cluster/.
# Re-running is safe: identities, key shares and passwords are kept, and the Consul registry is
# exported before its container is recreated and restored afterwards.
#
# Security layout (see mpc/PRODUCTION.md for a multi-host deployment):
#   - every request to the nodes needs two Ed25519 signatures: the signer's initiator key and
#     Laravel's authorizer key (MPC_AUTHORIZER_KEY in .env). The signer never sees the latter.
#   - NATS requires a password per role; the signer may only publish requests and read its own results.
#   - each node encrypts its share store with its own password, kept out of config.yaml.
set -euo pipefail
umask 077

MPCIUM_VERSION="${MPCIUM_VERSION:-eb109ae229f64d8d29a5ac35e19e95d7619129e1}"
NUM_NODES=3
DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$DIR")"
CLUSTER="${MPC_HOME:-$DIR/cluster}"
APP_ENV_FILE="${MPC_APP_ENV_FILE:-$ROOT/.env}"
PROJECT="${MPC_PROJECT:-ampuh-mpc}"
NATS_PORT="${MPC_NATS_PORT:-4222}"
CONSUL_PORT="${MPC_CONSUL_PORT:-8500}"
BIN="$DIR/bin"
export PATH="$BIN:$PATH" GOTOOLCHAIN=auto MPC_HOME="$CLUSTER"
COMPOSE=(docker compose -f "$DIR/docker-compose.yml")

for cmd in go docker node php openssl curl; do
    command -v "$cmd" >/dev/null || { echo "$cmd is required"; exit 1; }
done
docker info >/dev/null 2>&1 || { echo "Docker is installed but not running. Start Docker Desktop and re-run."; exit 1; }

# Mpcium's go.mod uses replace directives, so `go install pkg@version` refuses it; build from a checkout.
SRC="$DIR/.src/mpcium"
if [ ! -x "$BIN/mpcium" ] || [ ! -x "$BIN/mpcium-cli" ] || [ "$(git -C "$SRC" rev-parse HEAD 2>/dev/null)" != "$MPCIUM_VERSION" ]; then
    echo "Building mpcium + mpcium-cli ($MPCIUM_VERSION)..."
    [ -d "$SRC/.git" ] || git clone -q https://github.com/fystack/mpcium "$SRC"
    git -C "$SRC" fetch -q origin "$MPCIUM_VERSION" && git -C "$SRC" checkout -q --detach "$MPCIUM_VERSION"
    [ "$(git -C "$SRC" rev-parse HEAD)" = "$MPCIUM_VERSION" ] || { echo "mpcium checkout does not match $MPCIUM_VERSION"; exit 1; }
    mkdir -p "$BIN"
    (cd "$SRC" && go build -trimpath -o "$BIN/mpcium" ./cmd/mpcium && go build -trimpath -o "$BIN/mpcium-cli" ./cmd/mpcium-cli)
fi

mkdir -p "$CLUSTER"
chmod 700 "$CLUSTER"
cd "$CLUSTER"

secret() { [ -s "$1" ] || openssl rand -hex "${2:-32}" > "$1"; chmod 600 "$1"; cat "$1"; }

# Sets KEY=VALUE in the Laravel .env only when KEY is missing or empty.
set_app_env() {
    local key="$1" value="$2"
    [ -f "$APP_ENV_FILE" ] || return 0
    grep -Eq "^${key}=.+" "$APP_ENV_FILE" && return 0
    local tmp
    tmp="$(mktemp)"
    awk -v k="$key" -v v="$value" 'BEGIN{done=0} $0 ~ "^"k"=" {print k"="v; done=1; next} {print} END{if(!done) print k"="v}' "$APP_ENV_FILE" > "$tmp"
    cat "$tmp" > "$APP_ENV_FILE" && rm -f "$tmp"
    echo "  wrote $key to $(basename "$APP_ENV_FILE")"
}

app_env() { [ -f "$APP_ENV_FILE" ] && grep -E "^$1=" "$APP_ENV_FILE" | tail -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' || true; }

# --- NATS: one user per role -----------------------------------------------------------------
NATS_NODE_PASSWORD=$(secret .nats_node_password)
NATS_SIGNER_PASSWORD=$(secret .nats_signer_password)
bcrypt() { php -r 'echo str_replace("$2y$", "$2a$", password_hash($argv[1], PASSWORD_BCRYPT, ["cost" => 11]));' "$1"; }
CLIENT_ID="${MPC_CLIENT_ID:-ampuh}"

cat > nats.conf <<CONF
# Generated by mpc/setup.sh.
listen: 0.0.0.0:4222
http: 0.0.0.0:8222
max_payload: 1MB
jetstream { store_dir: /data, max_memory_store: 256MB, max_file_store: 2GB }

authorization {
  users = [
    # MPC nodes: trusted infrastructure, they own the streams.
    { user: mpc_node, password: "$(bcrypt "$NATS_NODE_PASSWORD")" }

    # Laravel's signer bridge: may submit keygen/signing requests and read its own results only.
    # It cannot publish results (so it cannot forge a wallet address or signature), touch peer
    # traffic, or create/delete streams.
    { user: mpc_signer, password: "$(bcrypt "$NATS_SIGNER_PASSWORD")", permissions: {
        publish: { allow: [
          "mpc.keygen_request.*",
          "mpc.signing_request.*",
          "\$JS.API.INFO",
          "\$JS.API.STREAM.INFO.mpc",
          "\$JS.API.CONSUMER.INFO.mpc.${CLIENT_ID}_keygen_result",
          "\$JS.API.CONSUMER.INFO.mpc.${CLIENT_ID}_signing_result",
          "\$JS.API.CONSUMER.CREATE.mpc.${CLIENT_ID}_keygen_result",
          "\$JS.API.CONSUMER.CREATE.mpc.${CLIENT_ID}_keygen_result.>",
          "\$JS.API.CONSUMER.CREATE.mpc.${CLIENT_ID}_signing_result",
          "\$JS.API.CONSUMER.CREATE.mpc.${CLIENT_ID}_signing_result.>",
          "\$JS.API.CONSUMER.DURABLE.CREATE.mpc.${CLIENT_ID}_keygen_result",
          "\$JS.API.CONSUMER.DURABLE.CREATE.mpc.${CLIENT_ID}_signing_result",
          "\$JS.API.CONSUMER.MSG.NEXT.mpc.${CLIENT_ID}_keygen_result",
          "\$JS.API.CONSUMER.MSG.NEXT.mpc.${CLIENT_ID}_signing_result",
          "\$JS.ACK.mpc.${CLIENT_ID}_keygen_result.>",
          "\$JS.ACK.mpc.${CLIENT_ID}_signing_result.>"
        ] }
        subscribe: { allow: ["_INBOX_${CLIENT_ID}.>"] }
    } }
  ]
}
CONF
chmod 600 nats.conf

# --- Consul: keep the registry across container recreation -------------------------------------
# Backups are timestamped and never overwritten, so a re-run can't replace a good backup with an
# empty registry.
consul_exported=0
if docker ps --format '{{.Names}}' | grep -qx "$PROJECT-consul"; then
    backup="consul-kv-backup-$(date +%Y%m%d-%H%M%S).json"
    if docker exec "$PROJECT-consul" consul kv export "" > "$backup.tmp" 2>/dev/null; then
        consul_exported=1
        if grep -q '"threshold_keyinfo/' "$backup.tmp"; then
            mv "$backup.tmp" "$backup"
            echo "Exported Consul registry to $CLUSTER/$backup"
        fi
    fi
    rm -f "$backup.tmp"
fi

# Containers from an older setup (another compose project, same names) block `up`. Their registry
# was exported above; remove the containers but keep their volumes as a fallback copy.
for svc in nats consul; do
    owner=$(docker inspect -f '{{index .Config.Labels "com.docker.compose.project"}}' "$PROJECT-$svc" 2>/dev/null || true)
    if docker inspect "$PROJECT-$svc" >/dev/null 2>&1 && [ "$owner" != "$PROJECT" ]; then
        if [ "$svc" = consul ] && [ "$consul_exported" != 1 ]; then
            echo "Refusing to replace $PROJECT-consul: could not export its registry (wallet key metadata)."
            echo "Start it (docker start $PROJECT-consul) and re-run."; exit 1
        fi
        echo "Replacing $PROJECT-$svc from older setup (project '${owner:-none}'); its volume is kept."
        docker rm -f "$PROJECT-$svc" >/dev/null
    fi
done

echo "Starting NATS + Consul..."
"${COMPOSE[@]}" up -d --remove-orphans
for _ in $(seq 1 60); do
    curl -sf "http://127.0.0.1:$CONSUL_PORT/v1/status/leader" | grep -q ':' && break
    sleep 1
done
curl -sf "http://127.0.0.1:$CONSUL_PORT/v1/status/leader" | grep -q ':' || { echo "Consul did not elect a leader"; exit 1; }

# Restore wallet key metadata into a fresh Consul. Liveness markers (ready/) are left out: the
# nodes write their own on startup.
backups_with_keys=$(grep -l '"threshold_keyinfo/' consul-kv-backup*.json 2>/dev/null || true)
latest_backup=""
[ -n "$backups_with_keys" ] && latest_backup=$(ls -t $backups_with_keys | head -1)
if [ -n "$latest_backup" ] && [ -z "$(docker exec "$PROJECT-consul" consul kv get -keys threshold_keyinfo/)" ]; then
    node -e 'const kv = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")); process.stdout.write(JSON.stringify(kv.filter((e) => !e.key.startsWith("ready/"))));' "$latest_backup" \
        | docker exec -i "$PROJECT-consul" consul kv import - >/dev/null
    restored=$(docker exec "$PROJECT-consul" consul kv get -keys threshold_keyinfo/ | wc -l | tr -d ' ')
    echo "Restored Consul registry from $latest_backup ($restored key metadata entries)"
fi

# --- Identities and keys ---------------------------------------------------------------------
[ -f peers.json ] || mpcium-cli generate-peers -n "$NUM_NODES"
[ -f event_initiator.key ] || mpcium-cli generate-initiator --algorithm ed25519
INITIATOR_PUBKEY=$(grep -o '"public_key": *"[^"]*"' event_initiator.identity.json | cut -d '"' -f4)

CHAIN_CODE=$(secret .chain_code)

# Laravel's authorizer key lives only in Laravel's .env; the nodes get its public half.
AUTHORIZER_KEY="${MPC_AUTHORIZER_KEY:-$(app_env MPC_AUTHORIZER_KEY)}"
if [ -z "$AUTHORIZER_KEY" ]; then
    AUTHORIZER_KEY=$(openssl rand -hex 32)
    set_app_env MPC_AUTHORIZER_KEY "$AUTHORIZER_KEY"
fi
AUTHORIZER_PUBKEY=$(node -e '
    const c = require("node:crypto");
    const k = c.createPrivateKey({ key: Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), Buffer.from(process.argv[1], "hex")]), format: "der", type: "pkcs8" });
    process.stdout.write(c.createPublicKey(k).export({ format: "der", type: "spki" }).subarray(-32).toString("hex"));
' "$AUTHORIZER_KEY")
AUTHORIZER_ID="${MPC_AUTHORIZER_ID:-ampuh-laravel}"

# Shared node config; mpcium-cli also reads it (for the Consul address) from the cwd.
# Secrets are not in here: NATS credentials come from NATS_URL and the Badger password from a
# per-node file, both passed by start.sh.
cat > config.yaml <<YAML
nats:
  url: nats://127.0.0.1:$NATS_PORT
consul:
  address: 127.0.0.1:$CONSUL_PORT
mpc_threshold: 2
environment: development
event_initiator_algorithm: ed25519
event_initiator_pubkey: "$INITIATOR_PUBKEY"
chain_code: "$CHAIN_CODE"
db_path: "."
backup_enabled: true
backup_period_seconds: 300
backup_dir: backups
max_concurrent_keygen: 2
max_concurrent_signing: 10
healthcheck:
  enabled: false
authorization:
  enabled: true
  required_authorizers:
    - $AUTHORIZER_ID
  authorizer_public_keys:
    $AUTHORIZER_ID:
      public_key: "$AUTHORIZER_PUBKEY"
      algorithm: ed25519
YAML
chmod 600 config.yaml

mpcium-cli register-peers --environment development

for i in $(seq 0 $((NUM_NODES - 1))); do
    node="node$i"
    mkdir -p "$node/identity"
    cp -f peers.json config.yaml "$node/"
    if [ ! -f "$node/identity/${node}_identity.json" ]; then
        (cd "$node" && mpcium-cli generate-identity --node "$node")
    fi
    # Each node gets its own share-store password. Clusters created before this change used one
    # shared password; existing stores keep it because Badger cannot be re-keyed in place.
    if [ ! -s "$node/.badger_password" ]; then
        if [ -d "$node/$node" ] && [ -s .badger_password ]; then
            cp .badger_password "$node/.badger_password"
        else
            # Badger uses the password bytes as the AES key: exactly 16, 24 or 32 bytes.
            openssl rand -base64 24 > "$node/.badger_password"
        fi
    fi
    case "$(tr -d '[:space:]' < "$node/.badger_password" | wc -c | tr -d ' ')" in
        16|24|32) ;;
        *) echo "$node/.badger_password must be 16, 24 or 32 characters"; exit 1 ;;
    esac
done

# Every node needs every other node's public identity.
for i in $(seq 0 $((NUM_NODES - 1))); do
    for j in $(seq 0 $((NUM_NODES - 1))); do
        [ "$i" = "$j" ] || cp -f "node$i/identity/node${i}_identity.json" "node$j/identity/"
    done
done

# --- Signer bridge ---------------------------------------------------------------------------
SIGNER_TOKEN="$(app_env MPC_SIGNER_TOKEN)"
if [ "${#SIGNER_TOKEN}" -lt 32 ]; then
    SIGNER_TOKEN=$(openssl rand -hex 32)
    [ -f "$APP_ENV_FILE" ] && grep -q '^MPC_SIGNER_TOKEN=' "$APP_ENV_FILE" && sed -i.bak '/^MPC_SIGNER_TOKEN=/d' "$APP_ENV_FILE" && rm -f "$APP_ENV_FILE.bak"
    set_app_env MPC_SIGNER_TOKEN "$SIGNER_TOKEN"
fi
RPC_URL="$(app_env BASE_RPC_URL)"
CHAIN_ID="$(app_env BASE_CHAIN_ID)"
SIGNER_PORT="$(app_env MPC_SIGNER_PORT)"

# The signer reads only this file, never Laravel's .env, so it cannot see the authorizer key.
cat > signer.env <<ENV
MPC_SIGNER_TOKEN=$SIGNER_TOKEN
MPC_SIGNER_PORT=${SIGNER_PORT:-7077}
MPC_NATS_URL=nats://127.0.0.1:$NATS_PORT
MPC_NATS_USER=mpc_signer
MPC_NATS_PASSWORD=$NATS_SIGNER_PASSWORD
MPC_CLIENT_ID=$CLIENT_ID
MPC_AUTHORIZER_ID=$AUTHORIZER_ID
MPC_INITIATOR_KEY_PATH=$CLUSTER/event_initiator.key
BASE_RPC_URL=${RPC_URL:-http://127.0.0.1:8545}
BASE_CHAIN_ID=${CHAIN_ID:-84532}
ENV

chmod -R go-rwx "$CLUSTER"

echo "Installing signer dependencies..."
(cd "$DIR/signer" && npm ci --silent --no-audit --no-fund)

echo
echo "MPC cluster ready in $CLUSTER. Start it with: npm run dev:mpc"
