<?php

return [
    /*
    | Order anchoring on Base (OP Stack L2).
    | Local development uses an anvil fork of Base Sepolia: see blockchain/README.md.
    */
    'base' => [
        'enabled' => env('BASE_ENABLED', false),
        'network_name' => env('BASE_NETWORK_NAME', 'Base Sepolia (local fork)'),
        'rpc_url' => env('BASE_RPC_URL', 'http://127.0.0.1:8545'),
        'chain_id' => (int) env('BASE_CHAIN_ID', 84532),
        'contract_address' => env('BASE_REGISTRY_ADDRESS'),
        'private_key' => env('BASE_RECORDER_PRIVATE_KEY'),
        // Leave empty for a local fork (no public explorer). Base Sepolia: https://sepolia.basescan.org
        'explorer_url' => env('BASE_EXPLORER_URL'),
    ],

    /*
    | Self-hosted MPC wallets: one 2-of-3 threshold key per buyer, generated by the
    | Mpcium cluster (mpc/). Laravel reaches it through the HTTP signer, and co-signs every
    | request with its authorizer key: the nodes refuse keygen/signing without that signature,
    | and Laravel only gives it to transactions that pass the policy below.
    */
    'mpc' => [
        'enabled' => env('MPC_WALLET_ENABLED', false),
        'signer_url' => env('MPC_SIGNER_URL', 'http://127.0.0.1:7077'),
        'signer_token' => env('MPC_SIGNER_TOKEN'),
        // Ed25519 seed (64 hex chars). Its public key is in every node's config.yaml.
        // Keep it on the Laravel host only; the signer must never see it.
        'authorizer_key' => env('MPC_AUTHORIZER_KEY'),
        'authorizer_id' => env('MPC_AUTHORIZER_ID', 'ampuh-laravel'),
        // Wallet ids must be unique per cluster: letters, digits, "-" and "_".
        'wallet_prefix' => env('MPC_WALLET_PREFIX', 'ampuh-user'),

        'limits' => [
            // Largest single transfer, and total sent per user in a rolling 24h window (ETH).
            'per_transfer_eth' => env('MPC_LIMIT_PER_TRANSFER_ETH', '1'),
            'daily_eth' => env('MPC_LIMIT_DAILY_ETH', '2'),
            // Refuse to co-sign when the network asks more than this per gas (gwei).
            'max_fee_gwei' => env('MPC_MAX_FEE_GWEI', '50'),
        ],
        // Blocks on top of the receipt before a transfer counts as confirmed.
        'confirmations' => (int) env('MPC_CONFIRMATIONS', 1),
    ],
];
